name: API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  api-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set Environment Variables
        run: |
          echo "BASE_URL=https://reqres.in/api" >> $GITHUB_ENV

      - name: Run API Tests
        run: |
          pytest -v